(define (problem p02)
    (:domain blocksword)
    (:objects a b c d e)
    (:init (encima_bloque a b) (encima_bloque b c) (encima_bloque c d) (encima_bloque d e) (encima_mesa e) (sin_nada_encima a) (brazo_libre))
    (:goal (and (encima_bloque e d) (encima_bloque d c) (encima_bloque c b) (encima_bloque b a) (encima_mesa a) (sin_nada_encima e) (brazo_libre)))
)